//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeminProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firmalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Firmalar()
        {
            this.Teminler = new HashSet<Teminler>();
        }
    
        public int Id { get; set; }
        public string FirmaAd { get; set; }
        public string YetkiliKisi { get; set; }
        public Nullable<int> FirmaTuru { get; set; }
        public string SicilNo { get; set; }
        public string VergiDairesi { get; set; }
        public string VergiNo { get; set; }
        public string TcNo { get; set; }
        public string Telefon { get; set; }
        public string Adres { get; set; }
        public string Email { get; set; }
        public string WebAdresi { get; set; }
        public string BankaAdi { get; set; }
        public string SubeAdi { get; set; }
        public string HesapOrIbanNo { get; set; }
    
        public virtual FirmaTurleri FirmaTurleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teminler> Teminler { get; set; }
    }
}
