//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeminProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeminDbEntities : DbContext
    {
        public TeminDbEntities()
            : base("name=TeminDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Firmalar> Firmalar { get; set; }
        public virtual DbSet<FirmaTurleri> FirmaTurleri { get; set; }
        public virtual DbSet<Teminler> Teminler { get; set; }
        public virtual DbSet<TeminSekilleri> TeminSekilleri { get; set; }
        public virtual DbSet<TeminTipleri> TeminTipleri { get; set; }
        public virtual DbSet<TeminTürleri> TeminTürleri { get; set; }
    }
}
