//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeminProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teminler
    {
        public int Id { get; set; }
        public string DosyaNo { get; set; }
        public string IsinAdi { get; set; }
        public int IsiYapanFirma { get; set; }
        public int TeminSekli { get; set; }
        public int TeminTuru { get; set; }
        public int TeminTipi { get; set; }
        public string Aciklama { get; set; }
        public string DosyaYolu { get; set; }
        public Nullable<System.DateTime> TeminTarihi { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public Nullable<decimal> FaturaTutar { get; set; }
    
        public virtual Firmalar Firmalar { get; set; }
        public virtual TeminSekilleri TeminSekilleri { get; set; }
        public virtual TeminTipleri TeminTipleri { get; set; }
        public virtual TeminTürleri TeminTürleri { get; set; }
    }
}
